### ISSUE TITLE
Decoding on MacOS gives raw data

### ISSUE THREAD

**Issue by justinvdk** [NaturalHistoryMuseum/pylibdmtx#24] opened 2018-06-11 10:29 UTC
Hi,

Executing the following code gives me unexpected results on MacOS:

```
from pystrich.datamatrix import DataMatrixEncoder
import PIL
from io import BytesIO
from pylibdmtx.pylibdmtx import decode

data = 'SomeStringWithData'

print(f'Encoding: {data}')

image_bytes = DataMatrixEncoder(data).get_imagedata(cellsize=2)
image = PIL.Image.open(BytesIO(image_bytes))

results = decode(image)

print('raw results:')
print(results)
```

Output on MacOS `10.13.3`:
```
Encoding: SomeStringWithData
raw results:
[Decoded(data=b'TpnfTusjohXjuiEbub\xb9AE\xbf}\xad|\xc81\xda\x9d\x9a\x95\xb2`\xf7`\x07\x01', rect=Rect(left=3, top=4, width=37, height=35))]
```
Whereas this works as expected on both Linux and Windows.

Basically it gives the raw data of the datamatrix instead of the parsed/decoded one.

I can't figure out whats going on because:
* `dmtxread` from `dmtx-utils` DOES work on the same machine, suggesting the c library IS NOT at fault here
* the `dmtxDecodeMatrixRegion` wrapper function gives the wrong result, suggesting the c library IS at fault.

I've also tried having the latest version of `libdmtx` compiled from source on my search path instead of the one from `homebrew` but it gives the same result.

Is this a known issue on your end maybe?

**Comment by superted6851** [comment] 2018-09-11 06:49
Downgrading to libdmtx to version 0.7.4 fixes the issue. Therefore I suggest the issue is with latest libdmtx and not pylibdmtx.

**Comment by akhmerov** [comment] 2018-11-05 23:29
I now observe this issue with libdmtx 0.7.5 and Ubuntu 18.10.

**Comment by jamespeterthornton** [comment] 2018-12-14 02:44
Hi @quicklizard99 @kursancew, have you had a chance to look at this? This seems to be a breaking issue on fresh installs of this repo. @jbweston's fix resolves it on my machine. His PR is ready to be merged, but additional information is needed on how to update CI to run with the newest version of libdmtx. 

(Although, some broader changes may be required if backwards compatibility with libdmtx is viewed as a necessity. Depending on scope, I can potentially help out as well in order to get this repo working again.)

**Comment by jamespeterthornton** [comment] 2018-12-14 18:43
Awesome, thank you!

**Comment by kursancew** [comment] 2018-12-19 03:21
could we use dmtxVersion() and a hack at the bottom of the file in the line of:
```
if ver_gt075:
    DmtxMessage._fields_.insert(5, ('fnc1', c_int))
    DmtxDecode._fields_.insert(3, ('fnc1', c_int))
    DmtxEncode._fields_.insert(8, ('fnc1', c_int))
```

**Closed** 2019-02-16 00:13 UTC

**Comment by quicklizard99** [comment] 2019-02-16 00:57
Included in v.0.1.8, now on PyPI.
